POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "Kata Mata",
	"number": "234567"
}

###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/635bc924c2f01354600cb228